# Generated by Django 4.0.1 on 2024-05-15 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_selectedworkout'),
        ('account', '0005_alter_customuser_gender_selectedworkout'),
    ]

    operations = [
    ]
