from django import forms

class HealthSignificantsForm(forms.Form):
    HEALTH_SIGNIFICANTS_CHECKES = (
        ('target_diet', '다이어트'),
        ('target_keep', '체중유지'),
        ('target_bulkup', '벌크업'),
        ('recommendexercise_yes','운동 추천받음'),
        ('recommendexercise_no','운동 추천거부'),
        ('exercise_selected_mon', '운동선택_월요일'),
        ('exercise_selected_tue', '운동선택_화요일'),
        ('exercise_selected_wed', '운동선택_수요일'),
        ('exercise_selected_thu', '운동선택_목요일'),
        ('exercise_selected_fri', '운동선택_금요일'),
        ('exercise_selected_sat', '운동선택_토요일'),
        ('exercise_selected_sun', '운동선택_일요일'),
        ('preference_inside', '실내운동'),
        ('preference_outdoor', '야외운동'),
        ('weight_high', '근력 운동이 익숙함'),
        ('weight_low', '근력 운동이 익숙하지 않음'),
        ('cardio_high', '유산소 운동이 익숙함'),
        ('cardio_low', '유산소 운동이 익숙하지 않음'),
        ('under1hour', '운동 시간 1시간 이내'),
        ('over1hour', '운동 시간 1시간 이상'),
        ('shoulder', '어깨 부상'),
        ('elbow', '팔꿈치 부상'),
        ('waist', '허리 부상'),
        ('knee', '무릎 부상'),
        ('recommenddiet_yes', '식단_추천받음'),
        ('recommenddiet_no', '식단_추천거부'),
        ('allergy_buckwheat', '알레르기_메밀'),
        ('allergy_wheat', '알레르기_밀'),
        ('allergy_soybean', '알레르기_대두'),
        ('allergy_peanut', '알레르기_땅콩'),
        ('allergy_walnut', '알레르기_호두'),
        ('allergy_pine_nut', '알레르기_잣'),
        ('allergy_sulfurousacids', '알레르기_아황산류'),
        ('allergy_peach', '알레르기_복숭아'),
        ('allergy_tomato', '알레르기_토마토'),
        ('allergy_eggs', '알레르기_계란'),
        ('allergy_milk', '알레르기_우유'),
        ('allergy_shrimp', '알레르기_새우'),
        ('allergy_macherel', '알레르기_고등어'),
        ('allergy_squid', '알레르기_오징어'),
        ('allergy_crab', '알레르기_게'),
        ('allergy_shellfish', '알레르기_조개류'),
        ('allergy_pork', '알레르기_돼지고기'),
        ('allergy_beef', '알레르기_쇠고기'),
        ('allergy_chicken', '알레르기_닭고기'),
        ('diet_selected_mon', '식단선택_월요일'),
        ('diet_selected_tue', '식단선택_화요일'),
        ('diet_selected_wed', '식단선택_수요일'),
        ('diet_selected_thu', '식단선택_목요일'),
        ('diet_selected_fri', '식단선택_금요일'),
        ('diet_selected_sat', '식단선택_토요일'),
        ('diet_selected_sun', '식단선택_일요일'),
        ('diet_selected_breakfast', '식단선택_아침'),
        ('diet_selected_lunch', '식단선택_점심'),
        ('diet_selected_dinner', '식단선택_저녁'),
        ('recommendsnack_yes', '간식_추천받음'),
        ('recommendsnack_no', '간식_추천거부'),
        ('snack_selected_morning', '간식선택_오전'),
        ('snack_selected_afternoon', '간식선택_오후'),
        ('snack_selected_night', '간식선택_밤'),
    )
    health_significants = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        choices=HEALTH_SIGNIFICANTS_CHECKES,
        required=False,
    )